
services:

  db:
    image: postgres
    restart: always
    env_file:
      - .cargo/config.toml
    environment:
      - POSTGRES_USER=${database_user}
      - POSTGRES_PASSWORD=${database_password}
      - POSTGRES_DB=${database_name}
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${database_name} -U $${database_user}"]
      interval: 1s
      timeout: 5s
      retries: 10
    

  meilisearch:
      image: 'getmeili/meilisearch:v1.10.1'
      env_file:
        - .cargo/config.toml
      environment:
          MEILI_MASTER_KEY: '${search_master_key}'
      ports:
          - '${search_port}:${search_port}'
      healthcheck:
          test: set -o pipefail;curl -fsS http://${search_server_url}/health | grep -q '{"status":"available"}'
          retries: 3
          timeout: 5s