name: rust-meilisearch-app-hello-world

services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATBASE_NAME}
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${DATABASE_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    

  meilisearch:
      image: 'getmeili/meilisearch:v1.10.1'
      env_file:
        - .env
      environment:
          MEILI_MASTER_KEY: '${SEARCH_MASTER_KEY}'
      ports:
          - '${SEARCH_PORT}:${SEARCH_PORT}'
      healthcheck:
          test: set -o pipefail;curl -fsS http://${SEARCH_SERVER_URL}/health | grep -q '{"status":"available"}'
          retries: 3
          timeout: 5s