name: rust-react-app-hello-world

services:

  db:
    container_name: postgres_server
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATBASE_NAME}
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${DATABASE_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
      